# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: sentimony records, electronic, psychedelic, free, download

port: 7777

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
