baseurl: 
include: ['_pages']
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json', 'assets/css/*.scss']
name: Sentimony Records
keywords: 'sentimony records, psychedelic, music, kyiv, ukraine'
