baseurl: 
name: Sentimony Records
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json', 'assets/css/*.scss']

# custom settings
keywords: 'sentimony records, psychedelic, music, kyiv, ukraine'
